#!/bin/bash
date=`date +%Y-%m-%d.%H:%M:%S`
modified=`git status | grep 'modified' | awk '{print $2}'`
pl='modified:'
for i in ${modified[@]}
do
    pl+=\ ${i}
done
git add -A
git commit -m "${pl}"
git push